name: "Tableau Workbook Action"
uses: jayamanikharyono/tableau-workbook-action@v1.3
with: 
  env: 
      PASSWORD: "${{ secrets.PASSWORD }}"
      SITE_ID: "${{ secrets.SITE_ID }}"
      TABLEAU_URL: "${{ secrets.TABLEAU_URL }}"
      USERNAME: "${{ secrets.USERNAME }}"
  repo_token: "${{ secrets.GITHUB_TOKEN }}"
on:
  pull_request:
      branches:
        - master
      paths:
        - 'tests/workbooks/**'
